import type { ProductRecord } from '../modules/products/product.service'

/** Full round-trip columns — matches MediOS upload template + product_id for re-import. */
export const PRODUCT_EXPORT_HEADERS = [
  'product_id',
  'product_name',
  'generic_name',
  'brand_name',
  'category',
  'company',
  'position_name',
  'unit_type',
  'description',
  'price_single',
  'price_pata',
  'price_box',
  'cost_price_single',
  'tax_percent',
  'tablets_per_strip',
  'strips_per_box',
  'stock_quantity',
  'batch_number',
  'expiry_date',
  'entry_date',
  'image_url',
  'stock_status',
] as const

export const PRODUCT_EXPORT_INSTRUCTIONS: string[][] = [
  ['MediOS product export — edit & re-upload'],
  [''],
  ['1. Edit product rows in the Products sheet (keep product_id unchanged).'],
  ['2. File → Download → Microsoft Excel (.xlsx)'],
  ['3. In MediOS Products page → Upload New Products → select the downloaded file.'],
  ['4. Rows with product_id will update existing products; rows without product_id add new ones.'],
  [''],
  ['Column', 'Required on upload', 'Notes'],
  ['product_id', 'For updates', 'Do not change when editing existing products'],
  ['product_name', 'Yes', 'Medicine name'],
  ['generic_name', 'Yes', 'Generic/salt name'],
  ['brand_name', 'Yes', 'Brand name'],
  ['category', 'No', 'e.g. Pain Relief, Gastric'],
  ['company', 'No', 'Manufacturer/supplier'],
  ['position_name', 'No', 'Storage location'],
  ['unit_type', 'Yes', 'tablet, capsule, syrup, injection, cream, drops, other'],
  ['description', 'No', 'Short description'],
  ['price_single', 'Yes', 'Price per single unit'],
  ['price_pata', 'No', 'Strip price'],
  ['price_box', 'No', 'Box price'],
  ['cost_price_single', 'No', 'Purchase cost per unit'],
  ['tax_percent', 'No', '0-100'],
  ['tablets_per_strip', 'No', 'Default 10'],
  ['strips_per_box', 'No', 'Default 10'],
  ['stock_quantity', 'Yes', 'Stock count'],
  ['batch_number', 'Yes', 'Batch/lot number'],
  ['expiry_date', 'Yes', 'YYYY-MM-DD'],
  ['entry_date', 'No', 'YYYY-MM-DD'],
  ['image_url', 'No', 'Optional product image URL'],
  ['stock_status', 'No', 'Read-only reference — ignored on upload'],
]

export function productRecordToExportRow(
  product: ProductRecord,
  stockStatus: string
): (string | number)[] {
  return [
    product.id,
    product.productName,
    product.genericName,
    product.brandName,
    product.category || '',
    product.company || '',
    product.positionName || '',
    product.unitType,
    product.description || '',
    product.priceSingle,
    product.pricePata ?? '',
    product.priceBox ?? '',
    product.costPriceSingle ?? '',
    product.taxPercent,
    product.tabletsPerStrip,
    product.stripsPerBox,
    product.stockQuantity,
    product.batchNumber,
    product.expiryDate,
    product.entryDate,
    product.imageUrl || '',
    stockStatus,
  ]
}
